title: 전쟁과여성인권박물관
baseURL: https://womenandwarmuseum.net

languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true
paginate: 16

build:
  writeStats: true

googleAnalytics:

taxonomies:
  tag: tags