main:
  - name: 박물관이용
    url: /guide
    weight: -110
  - name: 관람예약 및 안내
    url: /guide/admission
    weight: 1
    parent: 박물관이용
  - name: 오시는 길
    url: /guide/location
    weight: 2
    parent: 박물관이용
  - name: 뮤지엄 샵
    url: /guide/stores
    weight: 3
    parent: 박물관이용

  - name: 전시
    url: /exhibition
    weight: -100
  - name: 상설전시
    url: /exhibition
    weight: 1
    parent: 전시    
  - name: 소장품
    url: /items
    weight: 4
    parent: 전시

  - name: 자료실
    url: /archive
    weight: -90
  - name: 이달의 기록
    url: /archive/featured
    weight: 1
    parent: 자료실    
  - name: 기록물 이용
    url: /archive/usage
    weight: 2
    parent: 자료실
  - name: 기록물 기증
    url: /archive/donate
    weight: 3
    parent: 자료실

  - name: 소식/참여
    url: /connect
    weight: -80
  - name: 공지사항
    url: /connect/notice
    weight: 1
    parent: 소식/참여
  - name: 뉴스레터
    url: /connect/newsletter
    weight: 2
    parent: 소식/참여
  - name: 자원활동신청
    url: /connect/volunteer
    weight: 3
    parent: 소식/참여
  - name: 박물관 후원
    url: /connect/support
    weight: 4
    parent: 소식/참여

  - name: 박물관소개
    url: /about
    weight: -70
  - name: 인사말
    url: /about/greetings
    weight: 1
    parent: 박물관소개
  - name: 미션/비전
    url: /about/mission-and-vision
    weight: 2
    parent: 박물관소개
  - name: 연혁
    url: /about/history
    weight: 3
    parent: 박물관소개
  - name: 기부자의벽
    url: /about/donor-wall
    weight: 4
    parent: 박물관소개