# themeNoPipe: true

title: 전쟁과여성인권박물관
description: 일본군'위안부' 생존자들이 겪었던 역사를 기억하고 교육하는 공간
images:
  - img/site-feature-image.png
logo: images/logo-main.png

license:
  title_of_work: 전쟁과여성인권박물관
  link_to_work: https://www.womenandwarmuseum.net/
  createor_of_work: 팀두루미
  link_to_creator_profile: https://durumi.io
  year_of_creation: 2022

featuredImages:
  - image1.png
  - image2.jpg

bookingNaver: https://booking.naver.com/booking/6/bizes/596312

footer:
  전화: 02-392-5252
  팩스: 02-332-5256
  주소: 서울특별시 마포구 월드컵북로 11길 20
  사업자등록번호: 219-82-61946
  박물관후원계좌: KB국민은행 069137-04-021905 (예금주 / 전쟁과여성인권박물관) 
  이메일: museum@womenandwar.net
  url: https://www.womenandwarmuseum.net/
  fb: https://www.facebook.com/warwomenmuseum/
  youtube: https://www.youtube.com/channel/UCQD1q6jrJtLg8jXrora2jUg
  instagram: https://www.instagram.com/war_women_museum/?hl=ko

googleFonts:
  - https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@200&display=swap
  - https://fonts.googleapis.com/css2?family=Gothic+A1:wght@300;700&display=swap

cfImagePrefix: 'https://durumi.io/cdn-cgi/image'
cfImageStyles:
  thumb: 'fit=scale-down,width=300'
  thumbStores: 'fit=scale-down,width=800'
  full: 'fit=scale-down,width=1920'

stibee:
  accessToken: DONTCOMMIT
  endpointSubscribe: 'https://page.stibee.com/api/v1.0/lists'
  listIdSubscribe: 112752
  endpointEmailList: 'https://page.stibee.com/archives/105093/emails'
  listIdPublic: 105093