[build]
  command = "hugo mod get -u ./... && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.94.2"
  HUGO_ENV= "production"

[functions]
  directory = "functions/gsheet"
  node_bundler = "esbuild"
  external_node_modules = ["google-spreadsheet"]

[dev]
  command = 'hugo serve -D'
  functionsPort = 8889
  port = 8888
  targetPort = 1313


