backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'slides'
    label: '메인 슬라이드'
    folder: 'content/slides'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '순서', name: 'weight', widget: 'string' }    
      - { label: '상단메세지', name: 'upper_message', widget: 'string', required: false }
      - { label: '제목', name: 'title', widget: 'string', required: false }
      - { label: '부제목', name: 'sub_title', widget: 'string', required: false }
      - { label: '날짜', name: 'date', widget: 'datetime', required: false } 
      - { label: "슬라이드 배경이미지", name: "image", widget: "image" }
      - { label: '버튼제목', name: 'button_name', widget: 'string', required: false }
      - { label: '버튼URL', name: 'button_url', widget: 'string', required: false }
  - name: 'notice'
    label: '공지사항'
    folder: 'content/connect/notice'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '목록 고정', name: 'pinned', widget: 'boolean', default: false, hint: 'true 목록고정', required: false }
  - name: 'featured'
    label: '이달의 기록'
    folder: 'content/archive/featured'
    create: true
    slug: '{{slug}}' 
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }      
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '목록 고정', name: 'pinned', widget: 'boolean', default: false, hint: 'true 목록고정', required: false }       
  - name: 'previous'
    label: '주요 전시'
    folder: 'content/exhibition/previous'
    create: true
    slug: '{{slug}}' 
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }      
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '목록 고정', name: 'pinned', widget: 'boolean', default: false, hint: 'true 목록고정', required: false } 
  - name: 'programs'
    label: '프로그램'
    folder: 'content/learning-and-research/programs'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string', required: false }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '일시', name: 'date', widget: 'datetime', required: false }
      - { label: '접수기간', name: 'application_end_date', widget: 'string', required: false }
      - { label: '대상', name: 'program_target', widget: 'string', required: false }
      - { label: '모집인원', name: 'program_member', widget: 'string', required: false }
      - { label: '문의처', name: 'program_contact', widget: 'string', required: false }
      - { label: '프로그램 신청 접수 링크', name: 'apply_link', widget: 'string', required: false } 
      - { label: '대표이미지', name: 'image', widget: 'image' }
      - label: "첨부파일"
        name: "program_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true      
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '상시공개 프로그램 설정', name: 'always', widget: 'boolean', default: false, hint: 'true 상시공개 교육프로그램', required: false }      
      - { label: '목록 고정', name: 'pinned', widget: 'boolean', default: false, hint: 'true 목록고정', required: false }
      - { label: '관리화면 비노출', name: 'invisible', widget: 'boolean', default: false, required: false }
      - { label: '본문', name: 'body', widget: 'markdown' }      
  - name: 'resources'
    label: '교육자료'
    folder: 'content/learning-and-research/resources'
    create: true
    slug: '{{slug}}' 
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string', required: false }      
      - { label: '날짜', name: 'date', widget: 'datetime', required: false }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - label: "첨부파일"
        name: "resource_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '목록 고정', name: 'pinned', widget: 'boolean', default: false, hint: 'true 목록고정', required: false }
  - name: 'papers-ko'
    label: '연구자료(국문)'
    folder: 'content/learning-and-research/papers/ko'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - label: "첨부파일"
        name: "paper_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
  - name: 'papers-en'
    label: '연구자료(영문)'
    folder: 'content/learning-and-research/papers/en'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - label: "첨부파일"
        name: "paper_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
  - name: 'papers-jp'
    label: '연구자료(일문)'
    folder: 'content/learning-and-research/papers/jp'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - label: "첨부파일"
        name: "paper_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true
      - { label: '본문', name: 'body', widget: 'markdown' }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }      
  - name: 'volunteer'
    label: '자원활동신청'
    editor:
      preview: false
    files:
      - name: "volunteer"
        label: '자원활동신청 on/off'
        file: "content/connect/volunteer.md"
        fields:
          - { label: '자원활동신청 open', name: 'show_forms', widget: 'string', hint: 'open(열기) / close(닫기)' }